spring.application.name=budgetapp-backend
# PostgreSQL DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/budget_app
spring.datasource.username=postgres
spring.datasource.password=02hero
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true # ADD THIS LINE
# Server
server.port=8080
# Recommended for production-bound development
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.sql.init.mode=always
logging.level.org.springframework.jdbc.datasource.init=DEBUG
#Debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.OncePerRequestFilter=DEBUG 
# JWT Configuration
jwt.secret=WWQU3RCWZtNkzPqOSz0SqlkgmDUcxf5++UFFXUn3qIM=
jwt.expiration=3600000 
security.basic.enabled=false
management.security.enabled=false
